services:
  postgres:
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
  api:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 8080:8080
    env_file: .env
