spring:
  application:
    name: moe-count
  datasource:
    url: jdbc:postgresql://${DB_HOST:127.0.0.1}:${DB_PORT:5432}/${DATABASE:postgres}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}
    driverClassName: org.postgresql.Driver
  # flyway:
  #   enabled: true
  #   baseline-on-migrate: true
  #   locations: classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: update

