spring:
  application:
    name: moe-count
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/postgres
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  # flyway:
  #   enabled: true
  #   baseline-on-migrate: true
  #   locations: classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: update

